### ISSUE TITLE
Support for custom source sets

### ISSUE THREAD

**Issue by rgcostea** [simonharrer/gradle-modernizer-plugin#4]
The modernizer configuration allows users to specify includeTestClasses which is great.  But what if I define a custom source set like this?

```
    sourceSets {
        integration {
            java {
                srcDir "src/integration/java"
            }
            resources {
                srcDir "src/integration/resources"
            }
            compileClasspath = sourceSets.main.output + sourceSets.test.output + configurations.testCompile
            runtimeClasspath = output + compileClasspath + configurations.testRuntime
        }
    }

```
Have you considered adding support for this?  Thanks.

**Comment by simonharrer** [comment]
I simply mirror the options provided by the modernizer maven plugin. I do not plan to add more features on top of it. Sorry.
